// Prompt for the 'generate_cards' job — adding AI-generated cards to a
// stack that already went through normal extraction, rather than
// re-extracting a whole page from scratch (that's extract_page/
// pageExtraction.ts). Two callers, distinguished by whether an anchor card
// is given:
//   - "regenerate this card": anchorCard set — produce ONE revised card
//     capturing the same underlying content/intent as the anchor, shaped by
//     the instructions. The anchor itself is never modified by this job;
//     the caller inserts the new card immediately after it.
//   - "add more cards to this stack": anchorCard absent — produce however
//     many new cards the instructions call for, grounded in the same page,
//     never duplicating any of the stack's EXISTING CARDS.
//
// Deliberately its own (much shorter) system prompt rather than reusing
// pageExtraction.ts's SYSTEM_PROMPT wholesale: that prompt's central
// invariants (every source line must be covered, faithful-mode "vocabulary"/
// "grammar_rule" instead of "flashcard") are about extracting an entire page
// exactly once, which doesn't fit "add a few more targeted cards on top of
// an already-extracted page." Still reuses the exact same RECIPE_SCHEMA_SUMMARY/
// BLOCK_KINDS/output shape (see pageExtraction.ts) so output validates
// through the identical validatePage/validateBlock pipeline.

import { RECIPE_SCHEMA_SUMMARY, type ImageRegionInput } from './pageExtraction.ts';

export const GENERATE_CARDS_PROMPT_VERSION = 'generate-cards-v1';

export const SYSTEM_PROMPT = `You are adding new learning cards to an existing set of cards for a French-textbook reading app, generated from ONE source page.

Unlike a fresh extraction, this page has ALREADY been turned into cards once — you are given the EXISTING CARDS (all of them, or just the one being regenerated) and an admin's instructions describing what to add or change. Your job is to produce NEW cards per those instructions, never to redo the whole page.

TWO REQUEST SHAPES

- REGENERATE ONE CARD: you are given exactly one ANCHOR CARD plus instructions describing what should be different about it. Produce exactly ONE new card — a revised version capturing the same underlying content/teaching intent as the anchor, shaped by the instructions (e.g. a different recipe, a different framing, corrected/improved content). The anchor card itself stays untouched elsewhere in the system; you are only ever producing its replacement, never editing it in place.
- ADD MORE CARDS: no anchor card — just the full list of EXISTING CARDS already in this stack, for context. Produce as many new cards as the instructions reasonably call for (a small, focused set unless the instructions name a specific count). Every new card must be genuinely new content — never a near-duplicate of anything already in EXISTING CARDS.

GROUNDING

When a page image and/or numbered source lines are attached, ground new cards in that real content the same way normal extraction does: never invent French vocabulary, grammar points, or facts that aren't genuinely supported by the source or general knowledge relevant to it. When nothing is attached (a prompt-only stack), generate from your own knowledge, grounded by the instructions.

Every recall-style item (a vocabulary term, a grammar point, anything the learner should recall) is a "flashcard" card, never "vocabulary"/"grammar_rule"/a terms table — this is a generation-mode context, exactly like admin-instructed extraction. Its front/back/detail fields are authored by you (a natural translation, an example sentence, IPA, a usage tip), grounded in real content, never fabricated from nothing. Every interaction recipe's answer field gets your own best answer, even with no answer key attached — a wrong guess is acceptable, an empty answer field is not.

"translation" (a faithful, natural English translation of the card's own content) is required on every card with real content, generated by you, kept entirely separate from source_text. "source_text" should hold the real wording this card teaches — copied verbatim from the numbered source lines when you can point to one, or authored by you (same as a flashcard's own content) when there is nothing to copy from; never leave it empty on a card with real content. "source_line_ids" stays an empty array unless you are genuinely quoting specific numbered lines.

NEVER DUPLICATE EXISTING CONTENT — the single most important rule here, since this job only ever adds to what's already there. Read through EXISTING CARDS before generating anything; a new card must teach something those don't already cover (a different term, a different angle, a different piece of content), never restate one of them with different wording.

Tags: assign each card 0-4 tags from EXISTING TAGS below when one genuinely fits; propose a new one (short kebab-case) only when nothing existing fits and the concept is broad enough to recur elsewhere.

Return valid JSON only, matching the OUTPUT CONTRACT below. Do not use Markdown.

CARD RECIPES

${RECIPE_SCHEMA_SUMMARY}

OUTPUT CONTRACT

Return ONLY a single JSON object, no markdown, matching exactly:
{
  "blocks": [
    {
      "order_index": number,
      "kind": "document" | "interaction" | "image_ref" | "audio_ref",
      "component_type": string,
      "section_number": string | null,
      "title": string | null,
      "instruction": string | null,
      "translation": string | null,
      "category": string | null,
      "tags": ["string"] | null,
      "answer_key_status": "available" | "unavailable" | "unknown" | "inferred" | null,
      "source_line_ids": ["L001"],
      "source_text": "Exact or authored source wording",
      "content": {},
      "needs_review": boolean,
      "review_reason": string | null
    }
  ],
  "page_warnings": []
}

Before returning, silently verify: every new card is genuinely NOT a duplicate of anything in EXISTING CARDS; every recall-style card is a "flashcard"; every card with real content has a non-null translation and non-empty source_text; the JSON is valid.`;

export interface ExistingCardSummary {
  title: string | null;
  component_type: string;
  source_text: string;
  content: unknown;
}

export function buildGenerateCardsPrompt(input: {
  instructions: string;
  numberedSourceLines: string | null;
  imageRegions: ImageRegionInput[];
  existingCards: ExistingCardSummary[];
  anchorCard: ExistingCardSummary | null;
  existingTags: string[];
}): string {
  const hasSource = !!input.numberedSourceLines || input.imageRegions.length > 0;
  return [
    input.anchorCard
      ? 'Regenerate ONE card, replacing the ANCHOR CARD below per the instructions. Produce exactly one new card.'
      : 'Add more cards to this stack per the instructions below — as many as the instructions reasonably call for, never duplicating an EXISTING CARD.',
    '',
    'ADMIN INSTRUCTIONS',
    input.instructions,
    '',
    ...(input.anchorCard ? ['ANCHOR CARD (being regenerated — produce its replacement)', JSON.stringify(input.anchorCard), ''] : []),
    'EXISTING CARDS IN THIS STACK (never duplicate any of these)',
    input.existingCards.length ? JSON.stringify(input.existingCards) : '(none yet)',
    '',
    ...(hasSource
      ? [
          'NUMBERED SOURCE LINES (best-effort reading order — the attached page image, if any, is authoritative for structure/wording when they disagree)',
          input.numberedSourceLines ?? '(none — rely on the attached page image)',
          '',
          'DETECTED IMAGE REGIONS',
          JSON.stringify(input.imageRegions),
          '',
        ]
      : ['This stack has no source page image or text attached — generate from your own knowledge, grounded by the instructions above.', '']),
    'EXISTING TAGS (prefer these; propose a new one only when none fit)',
    input.existingTags.length ? input.existingTags.join(', ') : '(none yet)',
    '',
    'CARD RECIPES',
    RECIPE_SCHEMA_SUMMARY,
  ].join('\n');
}
